shes_the_first_sign_up_homepage:
    pattern:  /
    defaults: { _controller: ShesTheFirstSignUpBundle:Default:index }

shes_the_first_sign_up_logout:
    pattern:  /logout
    defaults: { _controller: ShesTheFirstSignUpBundle:Default:logout }